In [1]:
import pandas as pd

data_df = pd.read_csv('regilaul_vowels.csv')

data_df.head()

,Unnamed: 0.1,Unnamed: 0,word,syll,shape,index,segment,quantity,stressed,ictus,duration,midpoint,f1,f2,fileid,performer
0,0,0,sain,sain,CVVVC,0,ai,3,1,ictus,0.217500,4.263002,714.071536,1129.944778,41,LK
1,1,1,"mal´lika,",mal´,CVCC,0,a(i),2,1,off,0.179055,4.614738,946.021821,1448.348662,41,LK
2,2,2,"mal´lika,",li,CVV,1,i,2,0,ictus,0.130760,4.936603,574.096119,1864.237985,41,LK
3,3,3,mal´likast,mal´,CVCC,0,a(i),2,1,ictus,0.193353,5.891856,1075.429489,1570.329209,41,LK
4,4,4,mal´likast,li,CVV,1,i,2,0,off,0.122714,6.186455,589.298998,1688.844658,41,LK

In [2]:
r_df = data_df[["word","syll","shape","index","segment","quantity","stressed","ictus", "duration","f1","f2","fileid","performer"]].copy()
r_df.tail()

,word,syll,shape,index,segment,quantity,stressed,ictus,duration,f1,f2,fileid,performer
753,südant,dant,CVVCCC,1,ɑ,3,1,off,0.172132,654.258343,1112.070873,65,LK
754,sülle,sül,CVVC,0,yl,2,1,ictus,0.336953,640.080936,1706.830954,65,LK
755,sülle,le,CV,1,e,1,0,off,0.308579,721.464844,1631.467177,65,LK
756,rabadaie.,ra,CV,0,a,1,0,ictus,0.333783,935.850426,1478.448942,65,LK
757,rabadaie.,ba,CV,1,ɑ,1,0,off,0.319876,824.139440,1571.052387,65,LK

In [3]:
labels = {"index": "foot_i", "fileid":"song"}
#make labels more descriptive for summary stats 
pd.DataFrame.rename(r_df, columns=labels, inplace=True)
r_df.tail()

,word,syll,shape,foot_i,segment,quantity,stressed,ictus,duration,f1,f2,song,performer
753,südant,dant,CVVCCC,1,ɑ,3,1,off,0.172132,654.258343,1112.070873,65,LK
754,sülle,sül,CVVC,0,yl,2,1,ictus,0.336953,640.080936,1706.830954,65,LK
755,sülle,le,CV,1,e,1,0,off,0.308579,721.464844,1631.467177,65,LK
756,rabadaie.,ra,CV,0,a,1,0,ictus,0.333783,935.850426,1478.448942,65,LK
757,rabadaie.,ba,CV,1,ɑ,1,0,off,0.319876,824.139440,1571.052387,65,LK

In [4]:
#move to corpus builder!
#r_df.ictus = r_df.ictus.replace("x","off")
#r_df

In [5]:
r_df.segment.unique()

array(['ai', 'a(i)', 'i', 'e', 'a', 'iː', 'u', 'ɵ', 'ɛ', 'oː', 'y', 'ɑ',
       'ɪ', 'au', 'uː', 'eː', 'l', 'ʊ', 'æ', 'al', 'øː', 'o', 'ei', 'ae',
       'ee', 'aː', 'el', 'ell', 'ju', 'ull', 'ul', 'æi', 'ɵii', 'yyː',
       'eeː', 'oi', 'ɵi', 'ui', 'iiː', 'uiː', 'ɵː', 'il', 'yi', 'ja',
       'æː', 'yy', 'ɵɵ', 'ææ', 'oo', 'aa', 'ɵu', 'ol', 'ɵe', 'oe', 'ea',
       'øøː', 'eil', 'eiː', 'yl'], dtype=object)

In [6]:
#remove all the diphthongs (different phonematic status than long and overlong V)


#r_df = r_df[r_df['segment'].str.len() == 1]

#put off approximant codas until diphthong analysis: 
r_df = r_df[r_df['segment'].str.contains('l')==False]
r_df = r_df[r_df['segment'].str.contains('j')==False]
r_df = r_df[r_df['segment'].str.contains('ʎ')==False]
r_df = r_df[r_df['segment'].str.contains('y')==False]


r_df = r_df[r_df['segment'].str.contains('ei')==False]
r_df = r_df[r_df['segment'].str.contains('ea')==False]

r_df = r_df[r_df['segment'].str.contains('æi')==False]
r_df = r_df[r_df['segment'].str.contains('ui')==False]
r_df = r_df[r_df['segment'].str.contains('oi')==False]
r_df = r_df[r_df['segment'].str.contains('ae')==False]
r_df = r_df[r_df['segment'].str.contains('\(')==False]

r_df = r_df[r_df['segment'].str.contains('oe')==False]

r_df = r_df[r_df['segment'].str.contains('au')==False]
r_df = r_df[r_df['segment'].str.contains('ai')==False]
r_df = r_df[r_df['segment'].str.contains('yi')==False]
r_df = r_df[r_df['segment'].str.contains('ɵi')==False]
r_df = r_df[r_df['segment'].str.contains('ɵe')==False]
r_df = r_df[r_df['segment'].str.contains('ɵu')==False]




r_df.segment.unique()

array(['i', 'e', 'a', 'iː', 'u', 'ɵ', 'ɛ', 'oː', 'ɑ', 'ɪ', 'uː', 'eː',
       'ʊ', 'æ', 'øː', 'o', 'ee', 'aː', 'eeː', 'iiː', 'ɵː', 'æː', 'ɵɵ',
       'ææ', 'oo', 'aa', 'øøː'], dtype=object)

In [7]:
r_df["qual_id"] = r_df['segment'].str[0]
r_df.head()

,word,syll,shape,foot_i,segment,quantity,stressed,ictus,duration,f1,f2,song,performer,qual_id
2,"mal´lika,",li,CVV,1,i,2,0,ictus,0.130760,574.096119,1864.237985,41,LK,i
4,mal´likast,li,CVV,1,i,2,0,off,0.122714,589.298998,1688.844658,41,LK,i
7,"man´nipil´li,",ni,CVV,1,i,2,0,off,0.130770,493.465339,1222.836439,41,LK,i
8,petsariinist,pet,CVCC,0,e,2,0,ictus,0.182971,582.118843,1242.869852,41,LK,e
9,petsariinist,sa,CV,1,a,1,0,off,0.207942,830.665050,1462.704169,41,LK,a

In [8]:
#vowel space center of gravity for each performer 
dictS = {'LO': (569.6259050003295, 1415.8521323345387),
 'LK': (693.7620755684583, 1438.6183172232195),
 'MH': (758.0741804312802, 1679.2886667630698)}

In [9]:
fonelist = r_df.f1.tolist()
ftwoList = r_df.f2.tolist()
perfList = r_df.performer.tolist()

tupList = list(zip(fonelist,ftwoList,perfList))

In [10]:
from scipy.spatial import distance
#calculate euclidean distance from F1, F2 values
euclid = []
for element in tupList:
    fx, fy = element[0], element[1]
    key = element[2]
    p_s = dictS.get(key)
    euc = distance.euclidean(p_s,[fx,fy])
    euclid.append(euc)
    

r_df["euclid"] = euclid
r_df.tail()

/Users/sarah/miniconda3/envs/soundmines/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

,word,syll,shape,foot_i,segment,quantity,stressed,ictus,duration,f1,f2,song,performer,qual_id,euclid
751,"minna,",na,CVV,1,a,2,0,off,0.143127,577.812259,1171.895172,65,LK,a,290.836029
753,südant,dant,CVVCCC,1,ɑ,3,1,off,0.172132,654.258343,1112.070873,65,LK,ɑ,328.928226
755,sülle,le,CV,1,e,1,0,off,0.308579,721.464844,1631.467177,65,LK,e,194.828453
756,rabadaie.,ra,CV,0,a,1,0,ictus,0.333783,935.850426,1478.448942,65,LK,a,245.343123
757,rabadaie.,ba,CV,1,ɑ,1,0,off,0.319876,824.139440,1571.052387,65,LK,ɑ,185.841438

In [11]:
import os
vowel_df = "/Users/sarah/Git/regilaul_project/results/vowel_master.csv"
regi_clean = (open(vowel_df,'w'))
r_df.to_csv(regi_clean)
regi_clean.close()

In [12]:
r_df

,word,syll,shape,foot_i,segment,quantity,stressed,ictus,duration,f1,f2,song,performer,qual_id,euclid
2,"mal´lika,",li,CVV,1,i,2,0,ictus,0.130760,574.096119,1864.237985,41,LK,i,442.122204
4,mal´likast,li,CVV,1,i,2,0,off,0.122714,589.298998,1688.844658,41,LK,i,271.156332
7,"man´nipil´li,",ni,CVV,1,i,2,0,off,0.130770,493.465339,1222.836439,41,LK,i,294.415695
8,petsariinist,pet,CVCC,0,e,2,0,ictus,0.182971,582.118843,1242.869852,41,LK,e,225.347893
9,petsariinist,sa,CV,1,a,1,0,off,0.207942,830.665050,1462.704169,41,LK,a,139.005585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,"minna,",na,CVV,1,a,2,0,off,0.143127,577.812259,1171.895172,65,LK,a,290.836029
753,südant,dant,CVVCCC,1,ɑ,3,1,off,0.172132,654.258343,1112.070873,65,LK,ɑ,328.928226
755,sülle,le,CV,1,e,1,0,off,0.308579,721.464844,1631.467177,65,LK,e,194.828453
756,rabadaie.,ra,CV,0,a,1,0,ictus,0.333783,935.850426,1478.448942,65,LK,a,245.343123
757,rabadaie.,ba,CV,1,ɑ,1,0,off,0.319876,824.139440,1571.052387,65,LK,ɑ,185.841438